import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline': '#777683',
        'surface-dim': '#d7dadc',
        'error': '#ba1a1a',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed': '#001e2d',
        'on-surface': '#181c1e',
        'primary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#81cfff',
        'tertiary-fixed': '#c6e7ff',
        'on-secondary-container': '#003363',
        'primary-fixed-dim': '#c0c1ff',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e0e3e5',
        'primary-container': '#2e3192',
        'inverse-primary': '#c0c1ff',
        'surface-container': '#ebeef0',
        'surface-container-low': '#f1f4f6',
        'outline-variant': '#c7c5d4',
        'tertiary': '#002c40',
        'secondary-container': '#4f9dfd',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#4f54b4',
        'on-secondary-fixed-variant': '#004785',
        'on-primary': '#ffffff',
        'surface-bright': '#f7fafc',
        'secondary-fixed-dim': '#a5c8ff',
        'inverse-on-surface': '#eef1f3',
        'surface-container-high': '#e5e9eb',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#373a9b',
        'primary': '#15157d',
        'secondary': '#005faf',
        'secondary-fixed': '#d4e3ff',
        'on-surface-variant': '#464652',
        'on-background': '#181c1e',
        'on-primary-container': '#9da1ff',
        'on-tertiary-fixed-variant': '#004c6b',
        'tertiary-container': '#00435f',
        'surface-variant': '#e0e3e5',
        'surface': '#f7fafc',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#04006d',
        'on-secondary-fixed': '#001c3a',
        'background': '#f7fafc',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#31b4f2',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'gutter-mobile': '16px',
        'gutter-desktop': '24px',
        'margin-mobile': '16px',
        'unit': '4px',
        'margin-desktop': '32px',
        'touch-target-min': '48px',
      },
      fontFamily: {
        'label-mono': ['var(--font-jetbrains-mono)', 'monospace'],
        'body-lg': ['var(--font-ibm-plex-sans)', 'sans-serif'],
        'body-sm': ['var(--font-ibm-plex-sans)', 'sans-serif'],
        'headline-md': ['var(--font-ibm-plex-sans)', 'sans-serif'],
        'body-md': ['var(--font-ibm-plex-sans)', 'sans-serif'],
        'headline-lg': ['var(--font-ibm-plex-sans)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-ibm-plex-sans)', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-mono': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
